/* Change to reminders Database */
USE reminders;

ALTER TABLE reminders
ADD COLUMN IF NOT EXISTS month TINYINT UNSIGNED DEFAULT NULL AFTER date,
ADD COLUMN IF NOT EXISTS year INT(11) UNSIGNED DEFAULT NULL AFTER month,
ADD COLUMN IF NOT EXISTS hour TINYINT UNSIGNED DEFAULT NULL AFTER year,
ADD COLUMN IF NOT EXISTS minute TINYINT UNSIGNED DEFAULT NULL AFTER hour,
ADD COLUMN IF NOT EXISTS initial_reminder_run TINYINT(1) NOT NULL DEFAULT 0 AFTER expression,
ADD COLUMN IF NOT EXISTS recurrence_expression varchar(255) DEFAULT NULL AFTER initial_reminder_run,
ADD COLUMN IF NOT EXISTS is_recurring TINYINT(1) NOT NULL DEFAULT 0 AFTER recurrence_expression,
MODIFY COLUMN IF EXISTS day TINYINT UNSIGNED DEFAULT NULL,
MODIFY COLUMN IF EXISTS date TINYINT UNSIGNED DEFAULT NULL,
DROP COLUMN IF EXISTS run_once,
DROP COLUMN IF EXISTS time